sonar.projectKey=sonora-music-platform
sonar.organization=junmaes21
sonar.projectName=Sonora Music Platform
sonar.sources=backend,frontend
sonar.exclusions=**/bin/**,**/obj/**,**/node_modules/**,**/dist/**
